#!/bin/bash
# Create and push snort rules update
# To be ran by cron hourly

DBPATH=/var/db/apdp/SNORT
TMPD=`mktemp -d /tmp/apdp-SNORT-XXXXXX`

clean_tmpd() {
	rm -fr $TMPD
}

for CF in `ls $DBPATH/*.cf`; do
	PRODCODE=`basename $CF .cf`
	RDIR=$DBPATH/$PRODCODE
	CVER=`cat ${RDIR}.ver`
	PRODUCT=`head -n 1 $CF`

	UPVER=`wget -q -O - http://www.emergingthreats.net/version.txt`
	if [ "x$UPVER" == "x" ]; then
		echo "Failed to fetch update version info for $CF"
		clean_tmpd
		exit 1
	fi
	if [ "$UPVER" -eq "$CVER" ]; then
		continue
	fi
	if [ ! -f $TMPD/emerging.rules.tar.gz ]; then
		wget -q -c -O $TMPD/emerging.rules.tar.gz http://www.emergingthreats.net/rules/emerging.rules.tar.gz
		if [ "$?" != "0" ]; then
			echo "Failed to fetch emerging.rules.tar.gz"
			clean_tmpd
			exit 2
		fi
		tar xzf $TMPD/emerging.rules.tar.gz -C $TMPD/
	fi
	cp -a $RDIR $TMPD/$PRODCODE
	cp -a $TMPD/rules/* $TMPD/$PRODCODE/
	ln -sf $RDIR $TMPD/a
	ln -sf $TMPD/$PRODCODE $TMPD/b
	diff -puraN $TMPD/a $TMPD/b | sed "s,$TMPD/,," > $TMPD/$PRODCODE.patch
	echo "SNORT" > $TMPD/$PRODCODE.version
	echo >> $TMPD/$PRODCODE.version
	echo $PRODUCT >> $TMPD/$PRODCODE.version
	for patch in `ls $TMPD/*.patch`; do
		if [ "$patch" == "$TMPD/$PRODCODE.patch" ]; then
			continue
		fi
		cp -a $RDIR $TMPD/$PRODCODE.p
		patch -d $TMPD/$PRODCODE.p < $patch
		if [ "$?" == "0" ]; then
			diff -pqraN $TMPD/$PRODCODE $TMPD/$PRODCODE.p
			if [ "$?" == "0" ]; then
				COMPATPROD=`basename $patch .patch`
				echo $PRODUCT >> $TMPD/$COMPATPROD.version
				rm $TMPD/$PRODCODE.version
				break
			fi
		fi
		rm -fr $TMPD/$PRODCODE.p
	done
	echo "$UPVER" > ${RDIR}.ver
	patch -d $RDIR < $TMPD/$PRODCODE.patch
	rm -fr $TMPD/$PRODCODE
done

for verf in `ls $TMPD/*.version 2>/dev/null`; do
	BN=`basename $verf .version`
	gzip -9 $TMPD/$BN.patch
	apdp $TMPD/$BN.patch.gz $verf
done

clean_tmpd

exit 0