#!/bin/bash
# Create and push spamassassin rules update
# To be ran by cron hourly

DBPATH=/var/db/apdp/SPAMASSASSIN
TMPD=`mktemp -d /tmp/apdp-SPAMASSASSIN-XXXXXX`

clean_tmpd() {
	rm -fr $TMPD
}

for CF in `ls $DBPATH/*.cf`; do
	PRODCODE=`basename $CF .cf`
	RDIR=$DBPATH/$PRODCODE
	CVER=`cat ${RDIR}.ver`
	SUBDOMAIN=`tail -n 1 $CF`
	PRODUCT=`head -n 1 $CF`

	UPVER=`dig +noall +answer $SUBDOMAIN.updates.spamassassin.org TXT | grep -E -o \"[0-9]+\" | tr -d \"`
	if [ "x$UPVER" == "x" ]; then
		echo "Failed to fetch update version info for $CF"
		clean_tmpd
		exit 1
	fi
	if [ "$UPVER" -eq "$CVER" ]; then
		continue
	fi
	if [ ! -f $TMPD/$UPVER.tar.gz ]; then
		wget -q -c -O $TMPD/$UPVER.tar.gz http://www.sa-update.pccc.com/$UPVER.tar.gz
		if [ "$?" != "0" ]; then
			echo "Failed to fetch update file for $CF"
			clean_tmpd
			exit 2
		fi
		mkdir $TMPD/$UPVER
		tar xzf $TMPD/$UPVER.tar.gz -C $TMPD/$UPVER
	fi
	ln -sf $RDIR $TMPD/a
	ln -sf $TMPD/$UPVER $TMPD/b
	diff -puraN $TMPD/a $TMPD/b | sed "s,$TMPD/,," > $TMPD/$PRODCODE.patch
	echo "SPAMASSASSIN" > $TMPD/$PRODCODE.version
	echo >> $TMPD/$PRODCODE.version
	echo $PRODUCT >> $TMPD/$PRODCODE.version
	for patch in `ls $TMPD/*.patch`; do
		if [ "$patch" == "$TMPD/$PRODCODE.patch" ]; then
			continue
		fi
		cp -a $RDIR $TMPD/$PRODCODE
		patch -d $TMPD/$PRODCODE < $patch
		if [ "$?" == "0" ]; then
			diff -pqraN $TMPD/$PRODCODE $TMPD/$UPVER
			if [ "$?" == "0" ]; then
				COMPATPROD=`basename $patch .patch`
				echo $PRODUCT >> $TMPD/$COMPATPROD.version
				rm $TMPD/$PRODCODE.version
				break
			fi
		fi
		rm -fr $TMPD/$PRODCODE
	done
	echo "$UPVER" > ${RDIR}.ver
	patch -d $RDIR < $TMPD/$PRODCODE.patch
done

for verf in `ls $TMPD/*.version 2>/dev/null`; do
	BN=`basename $verf .version`
	gzip -9 $TMPD/$BN.patch
	apdp $TMPD/$BN.patch.gz $verf
done

clean_tmpd

exit 0