#!/bin/sh

certtool --generate-privkey --bits 4096 --outfile ca-key.pem
certtool --generate-self-signed --load-privkey ca-key.pem --outfile ca-cert.pem --template ca.cfg
certtool --generate-crl --load-ca-privkey ca-key.pem --load-ca-certificate ca-cert.pem --outfile crl.pem --template crl.cfg

certtool --generate-privkey --bits 4096 --outfile sman-key.pem
certtool --generate-certificate --load-privkey sman-key.pem --outfile sman-cert.pem --load-ca-certificate ca-cert.pem --load-ca-privkey ca-key.pem --template sman.cfg

certtool --generate-privkey --bits 2048 --outfile upgen-key.pem
certtool --generate-certificate --load-privkey upgen-key.pem --outfile upgen-cert.pem --load-ca-certificate sman-cert.pem --load-ca-privkey sman-key.pem --template upgen.cfg
cat sman-cert.pem >> upgen-cert.pem

certtool --generate-privkey --bits 2048 --outfile updateserv-key.pem
certtool --generate-certificate --load-privkey updateserv-key.pem --outfile updateserv-cert.pem --load-ca-certificate sman-cert.pem --load-ca-privkey sman-key.pem --template updateserv.cfg
cat sman-cert.pem >> updateserv-cert.pem

certtool --generate-privkey --bits 2048 --outfile ucertgen-key.pem
certtool --generate-certificate --load-privkey ucertgen-key.pem --outfile ucertgen-cert.pem --load-ca-certificate sman-cert.pem --load-ca-privkey sman-key.pem --template ucertgen.cfg
cat sman-cert.pem >> ucertgen-cert.pem

./makeusercert x86_64-generic "vyatta 6.2" 0001
