#!/bin/sh

FILE=$1
DBPATH=$2

if [ "x$FILE" = "x" -o "x$DBPATH" = "x" ]; then
	echo "Usage: apdc_place_incoming file database_path"
	exit 1
fi

if [ ! -f "$FILE" ]; then
	echo "Bad update file"
	exit 2
fi

if [ ! -d "$DBPATH" -o ! -f "$DBPATH/product" -o ! -d "$DBPATH/patches" ]; then
	echo "Bad database directory"
	exit 3
fi

PRODUCT=`cat $DBPATH/product | tail -n 1`
VER=`tar -O -x -z -f $FILE ./version | grep "$PRODUCT" | cut -f 2 -d :`

if [ "x$VER" = "x" ]; then
	echo "Bad update file contents"
	exit 4
else
	mv "$FILE" "$DBPATH/patches/$VER"
fi
