#!/bin/bash

CONFDIR=/etc/apdp
LOGF=/var/log/apdp-verificator-apds.log

PRDB=`cat $CONFDIR/apdp.conf | grep update_db_path | sed -r "s,^update_db_path[[:space:]]+\"(.*)\"$,\1,"`

apds 2>&1 | grep -E "([0-9]+):\ .*" --line-buffered | \
	sed -u -r "s,^,T," | while read LOGLINE; do
		echo $LOGLINE >> $LOGF
		if echo $LOGLINE | grep -q pushing; then
			read TAG AP < <(echo $LOGLINE | sed -r "s,^(T[0-9]+):\ pushing (.*)$,\1\t\2,")
			eval export $TAG=$AP
		elif echo $LOGLINE | grep -q request; then
			read TAG PRODUCT VERSION REVISION < <(echo $LOGLINE | sed -r "s,^(T[0-9]+):\ request:\ ([^ ]+)\ ([0-9.]+)\ ([0-9]+),\1\t\2\t\3\t\4,")

			if [ "x${!TAG}" != "x" ]; then
				ORIG=`echo "${!TAG}" | sed "s,${PRDB}/+,,"`
				ORIGDIR=`dirname $ORIG`
				TARB=`readlink $PRDB/$ORIG`
				TARBDIR=`dirname $TARB`
				cat $CONFDIR/apdp.externs | while read REMOTE; do
					MACHINE=`echo $REMOTE | cut -f 1 -d ':'`
					MPATH=`echo $REMOTE | cut -f 2 -d ':'`
					if ! ssh $MACHINE ls $MPATH/$ORIGDIR/$TARB >/dev/null 2>&1; then
						ssh $MACHINE mkdir -p $REMOTE/$ORIGDIR
						ssh $MACHINE mkdir -p $REMOTE/$ORIGDIR/$TARBDIR
						scp $PRDB/$ORIGDIR/$TARB $REMOTE/$ORIGDIR/$TARB
						ssh $MACHINE ln -s -f $TARB $REMOTE/$ORIG
					fi
				done
				eval export $TAG=
			fi
		elif echo $LOGLINE | grep -q "connection closed"; then
			if [ "${!TAG}" != "" ]; then
				Q=P$TAG
				echo "ALERT! Apdate ${!TAG} failed for ${!Q}" | mail -s "Apdate verificator message" admin@example.com
			fi
		fi
done
