#!/bin/sh
### BEGIN INIT INFO
# Provides:          apds
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Apdate server
# Description:       Apdate update system server
### END INIT INFO
#

. /lib/lsb/init-functions
PID=/var/run/apds.pid

start() {
	log_daemon_msg "Starting Apdate update server (verificator mode)" "apds"
	start-stop-daemon -p $PID -m -x /usr/lib/apdp/apdp_verificator -b -S
	log_end_msg "$?"
}

stop() {
	log_daemon_msg "Stopping Apdate update server (verificator mode)" "apds"
	start-stop-daemon -p $PID -K && rm -f $PID
	log_end_msg "$?"
}

restart() {
	stop
	start
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	restart
	;;
*)
	log_action_msg "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
