#!/bin/bash
# Apply squidguard update

DBPATH=/var/db/apdc
STAGE=$DBPATH/staging
RULESDIR=/var/lib/squidguard/db/blacklists

cmd=$1

patch_apply()
{
	if [ ! -f $STAGE/update ]; then
		echo "No update file in stage area $STAGE"
		exit 4
	fi
	set -e
	cp -a $RULESDIR $STAGE/backup
	touch $STAGE/backup_avail
	cd $RULESDIR && zcat $STAGE/update | patch -p1
	set +e
	squidGuard -P -C all &
}

backup_restore()
{
	if [ -f $STAGE/backup_avail ]; then
		cp -a $STAGE/backup/* $RULESDIR/
	fi
}


case $cmd in
	apply)
		patch_apply
		;;
	restore)
		backup_restore
		;;
	*)
		echo "Usage: $0 [apply|restore]"
		exit 3
		;;
esac

exit 0