#!/bin/bash
# Apply squidguard update

. `dirname $0`/unpackers-lib

DBDIR=/var/lib/squidguard/db/
PRODUCT=squidguard-lists

cmd=$1

patch_apply()
{
	TMPD=`mktemp -d /tmp/apdc-XXXXXX`
	BACKUP=`mktemp -d $DBPATH/backup-XXXXXX`

	set -e
	check_unpack_space "$patch" "$TMPD"
	cd $TMPD && zcat $patch | tar -x
	rm -f $patch
	check_delta_space "$TMPD/blacklists" "$DBDIR"
	if ! [ -f $TMPD/run ]; then
		apply_delta $DBDIR $TMPD/blacklists
		chown -R nobody:nogroup $DBDIR
	else
		cd $TMPD
		export APDATE_TMPD=$TMPD
		sudo -E /bin/bash $TMPD/run
	fi
	set +e
	squidGuard -C all && killall -HUP squidGuard &
	ionice -c 3 nice rm -fr $TMPD $BACKUP &
}

case $cmd in
	apply)
		patch=$2
		if [ ! -f $patch ]; then
			echo "Bad patch file passed"
			exit 25
		fi
		patch_apply
		;;
	restore)
		std_backup_restore
		;;
	*)
		echo "Usage: $0 [apply|restore]"
		exit 3
		;;
esac

exit 0
